"use client";

import { useEffect, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "";
type Branch = { id: string; name: string };
type Transfer = { id: string; status: string; fromBranch: string; toBranch: string; items: Array<{ productId: string; quantity: number }> };
export default function TransfersPage() {
  const [branches, setBranches] = useState<Branch[]>([]); const [transfers, setTransfers] = useState<Transfer[]>([]); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState("1"); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([fetch(`${API_URL}/api/v1/branches`, { credentials: "include" }), fetch(`${API_URL}/api/v1/inventory/transfers`, { credentials: "include" })]).then(async ([b, t]) => { if (b.status === 401) return window.location.assign("/login"); setBranches(await b.json()); setTransfers(await t.json()); }); }, []);
  async function createTransfer(event: React.FormEvent) { event.preventDefault(); const response = await fetch(`${API_URL}/api/v1/inventory/transfers`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ fromBranchId: from, toBranchId: to, items: [{ productId, quantity: Number(quantity) }] }) }); const result = await response.json(); setMessage(response.ok ? "Transfer created. Ship it from the API after reviewing the draft." : result.error ?? "Unable to create transfer."); if (response.ok) setTransfers((current) => [result, ...current]); }
  return <main className="dashboard-page"><header className="dashboard-nav shell"><a className="brand" href="/dashboard"><span className="brand-mark">L</span><span>ledgerly</span></a><nav><a href="/dashboard">Overview</a><a href="/branches">Branches</a><a className="active" href="/transfers">Transfers</a><a href="/billing">Billing</a></nav></header><section className="dashboard-content shell"><p className="eyebrow">Inventory operations</p><h1>Stock transfers</h1><form className="inline-form" onSubmit={createTransfer}><select value={from} onChange={(e) => setFrom(e.target.value)} required><option value="">From branch</option>{branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={to} onChange={(e) => setTo(e.target.value)} required><option value="">To branch</option>{branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select><input value={productId} onChange={(e) => setProductId(e.target.value)} placeholder="Product ID" required /><input type="number" min="1" value={quantity} onChange={(e) => setQuantity(e.target.value)} /><button className="button button-dark">Start transfer</button></form>{message && <p className="form-error">{message}</p>}<div className="dashboard-columns">{transfers.map((transfer) => <article className="dashboard-card" key={transfer.id}><div className="card-heading"><b>{transfer.fromBranch} → {transfer.toBranch}</b><span>{transfer.status}</span></div><p>{transfer.items.length} product lines</p></article>)}</div></section></main>;
}
